
SELECT E.NM_EQUIPE AS EQUIPE, P.NM_PILOTO AS PILOTO
  FROM tb_equipe AS E
  INNER JOIN tb_piloto AS P
  ON E.ID_EQUIPE = P.ID_EQUIPE
	ORDER BY EQUIPE;

-- questão 2
    
SELECT YEAR(DT_NASCIMENTO) AS "ANO NASCIMENTO", COUNT(NM_PILOTO) AS "PILOTOS" 
FROM TB_PILOTO
		GROUP BY YEAR(DT_NASCIMENTO) 
		ORDER BY "ANO NASCIMENTO";

-- questão 3 
        
SELECT NM_PILOTO, PAIS_PILOTO.NM_PAIS AS PAIS_PILOTO, NM_EQUIPE, PAIS_EQUIPE.NM_PAIS AS PAIS_EQUIPE, NR_COLOC_FINAL, NM_CIRCUITO
			FROM tb_piloto
				LEFT JOIN tb_pais PAIS_PILOTO
					ON tb_piloto.ID_PAIS = PAIS_PILOTO.ID_PAIS
				JOIN tb_equipe 
					ON tb_piloto.ID_EQUIPE = tb_equipe.ID_EQUIPE
				LEFT JOIN tb_pais PAIS_EQUIPE
					ON tb_equipe.ID_PAIS = PAIS_EQUIPE.ID_PAIS
				JOIN tb_resultado
					ON tb_piloto.ID_PILOTO = tb_resultado.ID_PILOTO
				JOIN tb_circuito
					ON PAIS_EQUIPE.ID_PAIS = tb_circuito.ID_PAIS
				JOIN tb_prova
					ON tb_circuito.ID_CIRCUITO = tb_prova.ID_CIRCUITO
ORDER BY NM_CIRCUITO, NR_COLOC_FINAL;